PAGOPA-111 create api to get stations and channels csv
pagopa/pagopa-api-config pull request #165
Opened 2022-12-01 16:57 UTC by FedericoRuzzier

#### List of Changes
Two APIs have been added: one to get all channels inside a csv file, one to get all stations inside a csv file.

#### Motivation and Context

#### How Has This Been Tested?
This addition has been tested via unit test in h2 environment

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-12-02 16:37 UTC, FedericoRuzzier commented
Csv canali:
<img width="786" alt="Screenshot 2022-12-02 alle 17 35 23" src="https://user-images.githubusercontent.com/49512050/205341065-b55f0e2e-7d70-4baf-a06c-d795f7be8d3d.png">

2022-12-05 10:27 UTC, FedericoRuzzier commented
Screenshots of the csv files are in the pr description

2022-12-07 16:01 UTC, jacopocarlini requested changes

2022-12-07 16:01 UTC, jacopocarlini commented on src/main/java/it/pagopa/pagopa/apiconfig/service/ChannelsService.java
> +                .map(elem -> Arrays.asList(deNull(elem.getFkIntermediarioPsp().getCodiceIntermediario()),
Can `getFkIntermediarioPsp()` return null?

2022-12-09 12:18 UTC, FedericoRuzzier commented on src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
> +    private String getEnvironment() {
CommonUtil makes all elements inside static, they cannot access `@Value` annotations. A workaround is to change it to `@Component` and autowiring it in the needed classes.

2022-12-09 14:40 UTC, jacopocarlini commented on src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
> +    private String getEnvironment() {
You can refactor the method in this way and pass the `@Value` from the components:
```suggestion
    private String getEnvironment(String env) {
```

2022-12-12 09:14 UTC, FedericoRuzzier commented on src/main/java/it/pagopa/pagopa/apiconfig/service/StationsService.java
> +    private String getEnvironment() {
Done 👍

2022-12-14 08:46 UTC, jacopocarlini approved these changes
Great 💪

2022-12-14 08:46 UTC, merged