Pcfg 31 get services
pagopa/pagopa-api-config pull request #40
Opened 2021-12-14 08:32 UTC by jacopocarlini

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-12-29 17:31 UTC, pasqualespica requested changes

2021-12-29 17:31 UTC, pasqualespica commented on openapi/swagger.json
> +        "operationId": "getBrokers_1",
could you verify `_1` ?

2021-12-29 18:09 UTC, jacopocarlini commented on openapi/swagger.json
> +        "operationId": "getBrokers_1",
resolved

2021-12-30 08:43 UTC, aomegax approved these changes
🧨

2021-12-30 08:48 UTC, merged