new collection postman
pagopa/pagopa-api-config pull request #43
Opened 2021-12-21 18:12 UTC by jacopocarlini

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-12-22 11:24 UTC, pasqualespica requested changes
update deploy pipelines

2021-12-22 11:24 UTC, pasqualespica commented on api-test/setup_env_api_test.sh
> +jq ".values[0].value = \"${HOSTPORT}\" | .values[1].value = \"${BASEPATH}\" | .values[2].value = \"${TENANT_ID}\" | .values[3].value = \"${CLIENT_ID}\" | .values[4].value = \"${CLIENT_SECRET}\" | .va
we should change `deploy-pipelines.yml`  ( `variables` section ) adding new vars `TENANT_ID` , `CLIENT_ID` , `CLIENT_SECRET` and `RESOURCE` according to [this one](https://github.com/pagopa/gitops/pull/214)

2021-12-22 13:36 UTC, jacopocarlini commented on api-test/ApiConfig.postman_collection.json
>  						"header": [
this call failed when is converted for k6 test because the header Content-Type is lost during conversion

2021-12-29 12:56 UTC, pasqualespica approved these changes
👍

2021-12-29 13:00 UTC, merged